export const INGREDIENTS_LOADING = 'INGREDIENTS_LOADING'
export const INGREDIENTS_LOADING_SUCCESSFULL = 'INGREDIENTS_LOADING_SUCCESSFULL'
export const INGREDIENTS_LOADING_FAILED = 'INGREDIENTS_LOADING_FAILED'
